// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3yTAoaMLLOw4kLy7cKOCpoXQk24nsBL0',
    appId: '1:925524119141:web:a1544b59c282578e0e808c',
    messagingSenderId: '925524119141',
    projectId: 'ec463miniprojectflutter',
    authDomain: 'ec463miniprojectflutter.firebaseapp.com',
    storageBucket: 'ec463miniprojectflutter.appspot.com',
    measurementId: 'G-VN6EJY7XB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8bVtpZQAJ2tdAqpuVeVhQUMH9AT6RAUM',
    appId: '1:925524119141:android:468a7a319dbef62f0e808c',
    messagingSenderId: '925524119141',
    projectId: 'ec463miniprojectflutter',
    storageBucket: 'ec463miniprojectflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2I9kRMmhE4j1wGZ532Bu7yEYk8hnrNns',
    appId: '1:925524119141:ios:f5908f5f96e00b450e808c',
    messagingSenderId: '925524119141',
    projectId: 'ec463miniprojectflutter',
    storageBucket: 'ec463miniprojectflutter.appspot.com',
    iosClientId: '925524119141-rfh9nk0a0d5rolhluptp3hiqdbgjkjio.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2I9kRMmhE4j1wGZ532Bu7yEYk8hnrNns',
    appId: '1:925524119141:ios:f5908f5f96e00b450e808c',
    messagingSenderId: '925524119141',
    projectId: 'ec463miniprojectflutter',
    storageBucket: 'ec463miniprojectflutter.appspot.com',
    iosClientId: '925524119141-rfh9nk0a0d5rolhluptp3hiqdbgjkjio.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitterApp',
  );
}
